#!/bin/sh

cd /opt/picoarch
./package
cp picoarch /opt/FunKey-OS/FunKey/board/funkey/rootfs-overlay/usr/games/
cp picoarch_funkey-s.opk /opt/FunKey-OS/FunKey/board/funkey/rootfs-overlay/usr/local/share/OPKs/Libretro/

cd ../FunKey-OS
make

rm -f FunKey/board/funkey/rootfs-overlay/usr/games/picoarch
rm -f FunKey/board/funkey/rootfs-overlay/usr/local/share/OPKs/Libretro/picoarch_funkey-s.opk
