################################################################################
#
# emu-gmenu2x-entries
#
################################################################################

EMU_GMENU2X_ENTRIES_VERSION = v1.0-funkey-s
EMU_GMENU2X_ENTRIES_SITE_METHOD = local
EMU_GMENU2X_ENTRIES_SITE = $(EMU_GMENU2X_ENTRIES_PKGDIR)opk
EMU_GMENU2X_ENTRIES_LICENSE = CC BY 4.0 Deed


ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_DOOM),y)
EMU_GMENU2X_ENTRIES_INSTALL += doom
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_DOSBOX),y)
EMU_GMENU2X_ENTRIES_INSTALL += dosbox
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_FBALPHA),y)
EMU_GMENU2X_ENTRIES_INSTALL += fbalpha
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_FC),y)
EMU_GMENU2X_ENTRIES_INSTALL += fc
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_NES),y)
EMU_GMENU2X_ENTRIES_INSTALL += nes
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_GB),y)
EMU_GMENU2X_ENTRIES_INSTALL += gb
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_GBC),y)
EMU_GMENU2X_ENTRIES_INSTALL += gbc
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_GBA),y)
EMU_GMENU2X_ENTRIES_INSTALL += gba
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_GBA_SP),y)
EMU_GMENU2X_ENTRIES_INSTALL += gba-sp
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_GG),y)
EMU_GMENU2X_ENTRIES_INSTALL += gg
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_GME),y)
EMU_GMENU2X_ENTRIES_INSTALL += gme
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_NGP),y)
EMU_GMENU2X_ENTRIES_INSTALL += ngp
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_MAME),y)
EMU_GMENU2X_ENTRIES_INSTALL += mame
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_MD_JA),y)
EMU_GMENU2X_ENTRIES_INSTALL += md-ja
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_MD_EU),y)
EMU_GMENU2X_ENTRIES_INSTALL += md-eu
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_GENESIS),y)
EMU_GMENU2X_ENTRIES_INSTALL += genesis
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_MSX),y)
EMU_GMENU2X_ENTRIES_INSTALL += msx
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_PCE),y)
EMU_GMENU2X_ENTRIES_INSTALL += pce
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_TG16),y)
EMU_GMENU2X_ENTRIES_INSTALL += tg16
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_PICO_8),y)
EMU_GMENU2X_ENTRIES_INSTALL += pico-8
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_POKEMINI),y)
EMU_GMENU2X_ENTRIES_INSTALL += pokemini
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_PS1),y)
EMU_GMENU2X_ENTRIES_INSTALL += ps1
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_SCUMMVM),y)
EMU_GMENU2X_ENTRIES_INSTALL += scummvm
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_SFC),y)
EMU_GMENU2X_ENTRIES_INSTALL += sfc
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_SNES),y)
EMU_GMENU2X_ENTRIES_INSTALL += snes
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_SMS),y)
EMU_GMENU2X_ENTRIES_INSTALL += sms
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_QUAKE),y)
EMU_GMENU2X_ENTRIES_INSTALL += quake
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_VCS),y)
EMU_GMENU2X_ENTRIES_INSTALL += vcs
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_WONDERSWAN),y)
EMU_GMENU2X_ENTRIES_INSTALL += wonderswan
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_WONDERSWAN_COLOR),y)
EMU_GMENU2X_ENTRIES_INSTALL += wonderswan-color
endif

ifeq ($(BR2_PACKAGE_EMU_GMENU2X_ENTRIES_PICOARCH),y)
EMU_GMENU2X_ENTRIES_INSTALL += picoarch
endif


define EMU_GMENU2X_ENTRIES_INSTALL_TARGET_CMDS
	$(INSTALL) -d -m 0755 $(TARGET_DIR)/usr/local/share/OPKs/Emulators
	for i in $(EMU_GMENU2X_ENTRIES_INSTALL) ; do \
		$(HOST_DIR)/usr/bin/mksquashfs $(EMU_GMENU2X_ENTRIES_PKGDIR)opk/$$i \
		$(TARGET_DIR)/usr/local/share/OPKs/Emulators/$$i-funkey-s.opk -all-root -noappend -no-exports -no-xattrs || exit 1 ; \
	done
endef

$(eval $(generic-package))
