#!/bin/sh

THIS=$(basename $0)

case "$1" in
    start)
	first_boot_ok=$(fw_printenv -n first_boot_ok 2>/dev/null)
	if ! [ ! "${first_boot_ok}" -ne "${first_boot_ok}" ] 2> /dev/null; then
	    first_boot
	fi
	!(hwclock) && date --set "2023-01-01 00:00:00" && hwclock -uw
	;;
    stop)
	;;
    *)
	echo "Usage: $0 {start|stop}" >&2
	exit 1
	;;
esac
