#!/bin/sh
#
# Start/stop poweroffthread
#

DAEMON=/usr/bin/poweroffprogram

case "$1" in
  start)
	start-stop-daemon --start --background --exec ${DAEMON}
	;;
  stop)
	pgrep poweroffprogram && (pgrep poweroffprogram | xargs kill -9)
	;;
  restart)
	${0} stop
	sleep 1 # Prevent race condition: ensure low_bat_check stops before start.
	${0} start
	;;
  *)
	echo "Usage: ${0} {start|stop|restart}"
	exit 1
esac
