#!/bin/sh

THIS=$(basename $0)

case "$1" in
    start)
	if audiosync start; then
	    echo "Starting audiosync: OK"
	    exit 0
	else
	    echo "Starting audiosync: ERROR"
	    exit 1
	fi
	;;
    stop)
	if audiosync stop >/dev/null 2>&1; then
	    echo "Stopping audiosync: OK"
	    exit 0
	else
	    echo "Stopping audiosync: ERROR"
	    exit 2
	fi
	;;
    *)
	echo "Usage: $0 {start|stop}" >&2
	exit 3
	;;
esac
